### ISSUE TITLE
gpg key for the packages missing

### ISSUE THREAD

**Issue by mdc-webdb** [dogukancagatay/logback-journal#31]
The files on https://central.sonatype.com/artifact/com.dgkncgty/logback-journal/overview are gpg signed.
But the public is not listed. So I'm not able to very the files of:
https://repo1.maven.org/maven2/com/dgkncgty/logback-journal/0.5.0/

So please and an link to the public gpg key.

**Comment by dogukancagatay** [comment]
The GPG keys ([FDBAC11ADB9D3C9E](https://keyserver.ubuntu.com/pks/lookup?search=FDBAC11ADB9D3C9E&fingerprint=on&op=index)) used to sign the maven artifacts are public and accessible. Otherwise, Sonatype doesn't allow the publishing of the artifact.

Anyway, I checked the GPG verification status, which seems valid.

```sh
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show \
  -Dartifact=com.dgkncgty:logback-journal:0.5.0
```

Let me know if the problem is still persisting.

**Comment by mdc-webdb** [comment]
Thanks, this will helps.
